git:
  depth: 100

language: generic

os:
  - linux

sudo: false

env:
  global:
    secure: qDzvmjcR6eLAmHx0ziN3Y5M8h65+OM+eBNERQsC3WSkeaD45rEE6a8w59dBdUzZBTLKO2RP8pKlgzxBZGOBlnLbTyN4RD/q2dA+gm5c0SDWWT4kVCiogJVsrzyRHVgMDmqDu56HPbQzhsW+5Qh2JKjVkkI7GwvGZRFB9WKQC8yjW/RfLvQ7bzX6jXbaHDYg9dywjI5u7da7HZKXyt/6nhebdaI19RdQHuESUqTADFEgdCKdzrNC+NqbJ8SUnNBBmkb1ZqoQ3/p1/Z/+uDi/2ThozE7Lz6gl8HtxVRnBiwNCDvZRE8uTB79+FlW0FJCVZ7qGO8jVWlVqy+WEEFh/6s9RP2PLd73CmItfF7BzSdxdurOYfnizboqCideSasDQK7XdeDiX4fPrgqbeesn8+XJ9vhxRAmpsNdZIU+2pivgviJwUZUwKwgzt3hf23ld9GpJg60wCfQRT8hiZc3/XsUPrzDjci7hwrRESqobPcuWk6xsFPTvJsTeOSLejP1wDOGAhufLTQIys26BSwHiaj6aI4RPK3Y4sy644m4IOfVvi3d+YfyN2Q5NO7QIwk5PjQBUEdwcIi3lAk2eAIjJamlDYFCRrnwuEoFinuFlUjtqpkuVTLgonTbk9KkIYnXeP3wYERrt4uOJtxDRCojBC0FI5rDbkhC3wP8Wef4EToQ+s=

stages:
  - test
  - name: anaconda_deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - &default
      stage: test
      env: PYTHON_VERSION="2.7"
      install: true
      script: true

    - <<: *default
      stage: anaconda_deploy
      env: PYTHON_VERSION="3.6"
      before_install:
        #######################
        ## install miniconda ##
        - easy_install --user doit==0.29.0 ioamdoit
        - ~/.local/bin/doit install_miniconda
        - rm -f .doit.db
        - export PATH="$HOME/miniconda/bin:$PATH"
        #######################
        - pip install ioamdoit
        - doit create_env --python=$PYTHON_VERSION
        - source activate test-environment
      install:
        - source deactivate
        - conda update -q -y conda
        - conda install -q -y conda-build anaconda-client
      script:
        - export VERSIONHACK=$(python -c "import subprocess;desc=subprocess.check_output(['git','describe','--long']).decode('utf8');v,commits=desc.split('-')[0:2];newv=[int(x) for x in v[1::].split('.')];newv[-1]+=1;print('.'.join(str(x) for x in newv)+'.dev'+commits)")
        - conda build conda.recipe/
        # TODO: need to upload only if package doesn't exist (as e.g. there are cron builds)
        - anaconda --token $CONDA_UPLOAD_TOKEN upload --user pyviz --label dev $(conda build --output conda.recipe)
