package:
  name: paramnb
  version: {{ os.environ.get("VERSIONHACK") }}

source:
  path: .

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - param >=1.5.1
    - ipywidgets >=5.2.2

test:
  imports:
    - paramnb

about:
  home: http://github.com/ioam/paramnb
  summary: Generate ipywidgets from Parameterized objects in the notebook
  license: BSD
